insert into codes(code, libelle, description) VALUES ('211', 'Hasina', '');
insert into codes(code, libelle, description) VALUES ('221', 'Ezaka sy fizakana ny fiaangonana', '');
insert into codes(code, libelle, description) VALUES ('222', 'Ezaka hariva', '');
insert into codes(code, libelle, description) VALUES ('223', 'Ezaka toilette', '');
insert into codes(code, libelle, description) VALUES ('224', 'Ezaka samihafa', '');
insert into codes(code, libelle, description) VALUES ('231', 'Tolotra voninkazo', '');
insert into codes(code, libelle, description) VALUES ('232', 'Tolotra sono', '');
insert into codes(code, libelle, description) VALUES ('233', 'Tolotra samihafa', '');
insert into codes(code, libelle, description) VALUES ('241', 'Seminera', '');
insert into codes(code, libelle, description) VALUES ('251', 'Voka-dehibe', '');

insert into codes(code, libelle, description) VALUES ('311', 'Haingo samihafa', '');
insert into codes(code, libelle, description) VALUES ('312', 'Kojakoja isan-karazany', '');
insert into codes(code, libelle, description) VALUES ('313', 'Fividianana isan-karazany', '');
insert into codes(code, libelle, description) VALUES ('314', 'Fikojakojana isan-karazany', '');
insert into codes(code, libelle, description) VALUES ('321', 'Fanampiana isan-karazany', '');
insert into codes(code, libelle, description) VALUES ('321', 'Karama', '');
insert into codes(code, libelle, description) VALUES ('341', 'Fanadiovana', '');
insert into codes(code, libelle, description) VALUES ('351', 'Adidy isan-karazany', '');
insert into codes(code, libelle, description) VALUES ('361', 'Ezaka miakatra', '');